"""add auth: hashed_password, is_admin, drop google_sub, refresh_tokens

Revision ID: 065876cc48e1
Revises: 03c21871904b
Create Date: 2026-10-07 21:22:27.195437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065876cc48e1'
down_revision: Union[str, None] = '03c21871904b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add REJECTED to native postgres enum (Alembic never autogenerates this).
    # DO block makes it idempotent and skips if type isn't a native enum.
    op.execute(
        """
        DO $$ BEGIN
            ALTER TYPE teacher_status ADD VALUE IF NOT EXISTS 'REJECTED';
        EXCEPTION WHEN undefined_object THEN NULL;
        END $$;
        """
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_teacher_id"), "refresh_tokens", ["teacher_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )

    # hashed_password: add with temporary server_default so existing rows don't break NOT NULL,
    # then drop the default (real value comes from app on every insert).
    op.add_column(
        "teachers",
        sa.Column("hashed_password", sa.String(), nullable=False, server_default=""),
    )
    op.alter_column("teachers", "hashed_password", server_default=None)

    # is_admin: same pattern.
    op.add_column(
        "teachers",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("teachers", "is_admin", server_default=None)

    op.drop_index(op.f("ix_teachers_google_sub"), table_name="teachers")
    op.drop_column("teachers", "google_sub")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('google_sub', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_teachers_google_sub'), 'teachers', ['google_sub'], unique=True)
    op.drop_column('teachers', 'is_admin')
    op.drop_column('teachers', 'hashed_password')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_teacher_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
